### ISSUE TITLE
回路の説明がおかしい

### ISSUE THREAD

**Issue by H1rono** [rogy-AquaLab/omniboat_robokit#134]
https://github.com/rogy-AquaLab/omniboat_robokit/blob/97bea266c21b82de73fa68bb6083cabb13125e6b/docs/02-construct-circuit.md?plain=1#L126-L130

既に4/26は過ぎているので

**Comment by H1rono** [comment]
XHにする必要がある

**Comment by Chikurin1014** [comment]
https://github.com/rogy-AquaLab/omniboat_robokit/blob/97bea266c21b82de73fa68bb6083cabb13125e6b/docs/02-construct-circuit.md?plain=1#L142-L150

X1とX7は使われていないので、消す

**Comment by Chikurin1014** [comment]
それに伴い写真も修整

**Comment by Chikurin1014** [comment]
修正箇所多いな、木曜あたりやるか

**Comment by H1rono** [comment]
これ、一回確認して大丈夫そうならcloseしてください

**Comment by H1rono** [comment]
@Chikurin1014 @rein0925
