### ISSUE TITLE
`pc`消す

### ISSUE THREAD

**Issue by H1rono** [rogy-AquaLab/omniboat_robokit#166]
使われてないこれ
#49

**Comment by H1rono** [comment]
`pc`が`Schneider`の構造に含まれているが使われていないので消す
https://github.com/rogy-AquaLab/omniboat_robokit/blob/45b507029e922faa6ac068a05c27f85a832880e4/include/schneider_model.hpp#L189

**Comment by Noir-swim** [comment]
もしかしてこれであってますか？？
リンクで記載してあったの構造のように
pcのループを消して、｛｝を加えてみたらエラーが消えました。
間違っていましたらヒントを教えていただきたいです。。。。
