### ISSUE TITLE
環境構築のドキュメントがわかりづらい

### ISSUE THREAD

**Issue by H1rono** [rogy-AquaLab/omniboat_robokit#57]

**Comment by H1rono** [comment]
https://github.com/rogy-AquaLab/omniboat_robokit/blob/main/docs/04-environment-setup.md

**Comment by H1rono** [comment]
- zipファイルを展開するくだりが短すぎる(スクショなどを加える？)

**Comment by Tokoroten2003** [comment]
トラブルシューティングがあった方がいいかも知れないと思った

例えば、
-  zip展開忘れ
-  platformioを入れ直す場合の手順
-  困ったら再起動すること
など

**Comment by H1rono** [comment]
#110

**Comment by H1rono** [comment]
またなんか出たら別にissue立てるということで
