### ISSUE TITLE
はんだ付けの説明

### ISSUE THREAD

**Issue by satoimotaro** [rogy-AquaLab/omniboat_robokit#66]
youtubeの動画が長すぎる、説明不足

**Comment by satoimotaro** [comment]
https://github.com/rogy-AquaLab/omniboat_robokit/blob/9052119d29748ea9ae34ad8e59dc32d2f26755ec/docs/02-construct-circuit.md?plain=1#L30-L32

**Comment by H1rono** [comment]
これは様子見
